### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by maloryowen** [cjlortie/Principles_for_environmental_challenges#4]
Cross off when figured out:
- [x] using kable did create table,  but didn't form a table in the pdf... issue with plos format?
- [x] getting book citations? how to get into a .bib when can't download it?

**Comment by cjlortie** [comment]
try this.
https://stackoverflow.com/questions/19997242/simple-manual-rmarkdown-tables-that-look-good-in-html-pdf-and-docx


How can I manually and simply format a table in RMarkdown that will look good when converted to HTML (using the knitr and markdown packages), PDF (using pandoc and miktex) and docx (using pandoc)?

I want to be able to write small tables in RMarkdown that are not a result of R functions that look good in the three formats I use most often. So far I've found a format that looks good in 2 of the 3 formats, is 3/3 possible?

One. This looks good after Knit HTML but not good in the PDF or docx

<table>
<tr>
<td>Eggs</td>
<td>Ham</td>
</tr>
<tr>
<td>Basil</td>
<td>Tomato</td>
</tr>
</table>
Two. This one looks good after Knit HTML but not good in the PDF or docx

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
Three. This one does not look good after Knit HTML but is good in the PDF and docx (best option so far)

**Comment by cjlortie** [comment]
getting book citations? how to get into a .bib when can't download it?

Just open bib and do by hand. emulate style.

**Comment by cjlortie** [comment]
need missing citations added to .bib now.
pandoc-citeproc: reference Baron2010 not found
pandoc-citeproc: reference Baker2016 not found
pandoc-citeproc: reference Ruxton2017 not found
pandoc-citeproc: reference Samie2018 not found
pandoc-citeproc: reference Congrad2011 not found
pandoc-citeproc: reference Stoops2017 not found
! LaTeX Error: Environment longtable undefined.

**Comment by cjlortie** [comment]
got it.
